import java.util.*;

public class NumberGuessingGame {

    // Method to play a single round of the guessing game
    static void playGame() {
        int targetNumber; // The number generated by the computer
        int playerGuess;  // The player's guess
        int numberOfGuesses; // Count of guesses made by the player

        // Generate a random number between 1 and 100
        targetNumber = (int)(100 * Math.random()) + 1;

        // Initialize the number of guesses
        numberOfGuesses = 0;

        System.out.println();
        System.out.println("Enter your first guess:");

        Scanner scanner = new Scanner(System.in);

        while (true) {
            playerGuess = scanner.nextInt(); // Get the player's guess

            numberOfGuesses++; // Increase the guess count

            // If the guess is correct, congratulate the player and exit the loop
            if (playerGuess == targetNumber) {
                System.out.println("Congratulations! You've guessed it in " + numberOfGuesses + " tries! The number was " + targetNumber);
                break;
            }

            // If the player reaches the maximum number of guesses, end the game
            if (numberOfGuesses == 6) {
                System.out.println("Sorry, you've used all 6 attempts.");
                System.out.println("The correct number was " + targetNumber);
                break;
            }

            // Provide hints to the player
            if (playerGuess < targetNumber) {
                System.out.println("Too low. Try again:");
            } else {
                System.out.println("Too high. Try again:");
            }
        }

        System.out.println();
        scanner.close();
    }

    // Main method to start the game
    public static void main(String[] args) {
        System.out.println("Welcome to the Number Guessing Game!");
        System.out.println("I've chosen a number between 1 and 100. Can you guess it?");

        Scanner scanner = new Scanner(System.in);

        boolean continuePlaying;

        // Loop to allow the player to play multiple rounds
        do {
            playGame();

            // Ask the player if they want to play another round
            System.out.println("Do you want to play again? (Y/N)");

            String response = scanner.next();
            continuePlaying = response.equalsIgnoreCase("Y");
        } while (continuePlaying);

        // Exit message
        System.out.println("Thanks for playing! Goodbye.");
        scanner.close();
    }
}
